name: untitled2
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  bloc: ^9.0.0
  carousel_slider: ^5.0.0
  change_app_package_name: ^1.4.0
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_compass: ^0.8.1

  flutter_bloc: ^9.0.0
  flutter_launcher_icons: ^0.14.2
  flutter_map_location_marker: ^9.1.1
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.17
  fluttertoast: ^8.2.10
  geolocator: ^13.0.2
  hexcolor: ^3.0.1
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.3.5
  smooth_page_indicator: ^1.2.0+3
  image_picker: ^1.1.2

dev_dependencies:
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.4
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.2

flutter_native_splash:
  # color: "#8ed9e9"
  color: "#ffffff"
  image: assets/images/logo4x.png
#  branding: assets/images/logo.png
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
